### ISSUE TITLE
Allthemods3 / Chunkloading broken with update.

### ISSUE THREAD

**Issue by Crosis247** [McJackGaming/McJackGaming#10]
Iron/Diamond chunk loaders currently not working. All other chunk loading options banned or disabled.

**Comment by BaggedTaco** [comment]
I am also having this issue.

**Comment by Sharkske** [comment]
i did some digging the chunkloaders got broken due to the new panel i need to do some changing things around they arent connecting to mysql for some reason i will track down why tomorrow ty for pointing that our crosis

**Comment by Sharkske** [comment]
Ok its fixed BCL can now connect to the Mysql db, so basically chunk-loading is back to normal!!! enjoy sorry
