### ISSUE TITLE
Allthemods3 / Random AFKs

### ISSUE THREAD

**Issue by Crosis247** [McJackGaming/McJackGaming#12]
Server randomly putting everyone afk at random while moving around / being active.

**Comment by BaggedTaco** [comment]
It keeps telling me I'm AFK when I'm not.

**Comment by Falney** [comment]
Saw people being randomly disconnected from the server due to this glitch

**Comment by Sharkske** [comment]
The afk thing im unsure prob needs a plugin update ill apply that as soon as i can

**Comment by mrqs001** [comment]
Its fixed bug with ftbutilities.
