### ISSUE TITLE
Crashing from Stoneblock

### ISSUE THREAD

**Issue by DaveRambo91** [McJackGaming/McJackGaming#17]
I can log in to Stoneblock but my ping skyrockets and then I crash with the tag: Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host" I'm not sure what to do to fix this, but any help would be greatly appreciated.  I love playing on your servers, but with this problem I am having a hard time doing so.

**Comment by Cliff311** [comment]
Hi Dave. I hope to help you.

Try the following steps. If that doesn't work, please respond back with a copy and paste of below questions with your answers and if you could, attach a link to your crash log. Thanks!

**Step 1**
Ensure you are force using the latest Java.

For twitch, you'll need to force use JAR launcher with latest java 1.8.0.161, as the native launcher uses an old java Version 1.8.0.25 (will also fix IE manual crashes)

For FTB Launcher, you'll need to go into settings and select your specific Java. Ensure that you have either 32bit or 64bit computer and get the correct version of Java.

**Step 2**
Allocate at minimum 4GB of ram to the server. If running on 64bit computer and java, please allocate at minimum 10GB.

**Step 3**
Attempt an alternative launcher. Some solid options are MMC, twitch, forge and FTB.

**Questions**
1. Do you have the correct version of stone block installed? _Check the web page, not the sign over the portal_
2. At what time during the day are you trying to log in? Please put time zone :)
3. Have you attempted to do a /spawn. Potential area lag issues can be cleared this way.
4. Are others able to join?
