### ISSUE TITLE
Thaumcraft at infinity server

### ISSUE THREAD

**Issue by RootinPutin** [McJackGaming/McJackGaming#9]
Hello :D Friend and I are playing at the infinity server and want to play with the thaumcraft mod but appearently it doesn't work propertly. The research function at the research table doesn't work. Is thaumcraft banned from the server or are we just too stupid ? 
sincerely me, :)

**Comment by Sharkske** [comment]
Sorry about that i can inform you that it works, you just have to use the direct IP: inf.mcjackgames.com
